### ISSUE TITLE
Task failing prematurely unsure as to what the error is

### ISSUE THREAD

**Issue by ControlCplusControlV** [ControlCplusControlV/Golem-Shard#2]
```[2021-10-29T19:42:14.846-0700 DEBUG yapapi] Yapapi version: 0.6.2, script: requestor.py, working directory: /home/controlc/Downloads/shardt
[2021-10-29T19:42:14.846-0700 INFO yapapi] Using log file `hello.log`; in case of errors look for additional information there
[2021-10-29T19:42:14.865-0700 DEBUG yapapi.executor] Creating allocation using payment platform `zksync-rinkeby-tglm`
[2021-10-29T19:42:16.117-0700 DEBUG yapapi.services] Starting new Cluster 1: 1x[Service: ShardService, Payload: _VmPackage(repo_url='http://girepo.dev.golem.network:8000', image_hash='0a4c65ecfd19a1f45e1f9cf77a2da633fcb22f1dea786c261d26af46', constraints=_VmConstraints(min_mem_gib=4, min_storage_gib=16.0, min_cpu_threads=1, runtime='vm'))]
[2021-10-29T19:42:16.119-0700 DEBUG yapapi.services] spawning instance within Cluster 1: 1x[Service: ShardService, Payload: _VmPackage(repo_url='http://girepo.dev.golem.network:8000', image_hash='0a4c65ecfd19a1f45e1f9cf77a2da633fcb22f1dea786c261d26af46', constraints=_VmConstraints(min_mem_gib=4, min_storage_gib=16.0, min_cpu_threads=1, runtime='vm'))]
[2021-10-29T19:42:16.416-0700 DEBUG yapapi.events] SubscriptionCreated(sub_id='da9538c5986f47ae8b8af896177eb24c-61ae134d9e6d3d5caa462a2092100a9568f8d551f335e4ab3840554d109039a5')
[2021-10-29T19:42:16.547-0700 DEBUG yapapi.events] ProposalReceived(prop_id='R-dd3f605a70cc1dee5159352b5ba4e128e74d8eda49e1dd9350a928c55b679f13', provider_id='0x046fe196e8eb4900d2c1aba91a01d4523ad9fbe5')
[2021-10-29T19:42:16.547-0700 DEBUG yapapi.strategy.LeastExpensiveLinearPayuMS] Scoring offer R-dd3f605a70cc1dee5159352b5ba4e128e74d8eda49e1dd9350a928c55b679f13, parameters: ComLinear(scheme=<BillingScheme.PAYU: 'payu'>, price_model=<PriceModel.LINEAR: 'linear'>, fixed_price=0.0, price_for={<Counter.TIME: 'golem.usage.duration_sec'>: 0.0, <Counter.CPU: 'golem.usage.cpu_sec'>: 0.0})
[2021-10-29T19:42:16.547-0700 DEBUG yapapi.executor] Scored offer R-dd3f605a70cc1dee5159352b5ba4e128e74d8eda49e1dd9350a928c55b679f13, provider: TroggoMan_1, strategy: DecreaseScoreForUnconfirmedAgreement, score: 99.009901
[2021-10-29T19:42:16.549-0700 DEBUG yapapi.strategy.LeastExpensiveLinearPayuMS] Scoring offer R-cd390a4f8e080fc107724660662e32fc1c179cb51d5836d12bb716c053e15fba, parameters: ComLinear(scheme=<BillingScheme.PAYU: 'payu'>, price_model=<PriceModel.LINEAR: 'linear'>, fixed_price=0.0, price_for={<Counter.TIME: 'golem.usage.duration_sec'>: 5.555555555555556e-06, <Counter.CPU: 'golem.usage.cpu_sec'>: 2.777777777777778e-05})
[2021-10-29T19:42:16.549-0700 DEBUG yapapi.executor] Scored offer R-cd390a4f8e080fc107724660662e32fc1c179cb51d5836d12bb716c053e15fba, provider: erar02, strategy: DecreaseScoreForUnconfirmedAgreement, score: 98.814229
[2021-10-29T19:42:16.550-0700 DEBUG yapapi.strategy.LeastExpensiveLinearPayuMS] Scoring offer R-ed9e87d1260c15739a6e299a6aa16a0068647f1bb391d35448a825b9031bb519, parameters: ComLinear(scheme=<BillingScheme.PAYU: 'payu'>, price_model=<PriceModel.LINEAR: 'linear'>, fixed_price=0.004, price_for={<Counter.TIME: 'golem.usage.duration_sec'>: 0.0008333333333333334, <Counter.CPU: 'golem.usage.cpu_sec'>: 0.0008333333333333334})
[2021-10-29T19:42:16.550-0700 DEBUG yapapi.executor] Scored offer R-ed9e87d1260c15739a6e299a6aa16a0068647f1bb391d35448a825b9031bb519, provider: cooing-lift, strategy: DecreaseScoreForUnconfirmedAgreement, score: 89.766607
[2021-10-29T19:42:16.550-0700 DEBUG yapapi.events] ProposalReceived(prop_id='R-cd390a4f8e080fc107724660662e32fc1c179cb51d5836d12bb716c053e15fba', provider_id='0x35f14eb8d8e4b0685199115c563280916cc90ce7')
[2021-10-29T19:42:16.550-0700 DEBUG yapapi.events] ProposalReceived(prop_id='R-ed9e87d1260c15739a6e299a6aa16a0068647f1bb391d35448a825b9031bb519', provider_id='0xa2eb4174bd8bd9be5978938bc4be2dccb985298d')
[2021-10-29T19:42:16.848-0700 DEBUG yapapi.events] ProposalResponded(prop_id='R-ed9e87d1260c15739a6e299a6aa16a0068647f1bb391d35448a825b9031bb519')
[2021-10-29T19:42:16.903-0700 DEBUG yapapi.events] ProposalResponded(prop_id='R-cd390a4f8e080fc107724660662e32fc1c179cb51d5836d12bb716c053e15fba')
[2021-10-29T19:42:17.017-0700 DEBUG yapapi.events] ProposalResponded(prop_id='R-dd3f605a70cc1dee5159352b5ba4e128e74d8eda49e1dd9350a928c55b679f13')
[2021-10-29T19:42:17.020-0700 DEBUG yapapi.events] ProposalReceived(prop_id='R-969788ffd4ee4e533ce1c774aa9a0cbb37e01a1e9e5f398a25a95ff37dac8cb9', provider_id='0xa2eb4174bd8bd9be5978938bc4be2dccb985298d')
[2021-10-29T19:42:17.020-0700 DEBUG yapapi.strategy.LeastExpensiveLinearPayuMS] Scoring offer R-969788ffd4ee4e533ce1c774aa9a0cbb37e01a1e9e5f398a25a95ff37dac8cb9, parameters: ComLinear(scheme=<BillingScheme.PAYU: 'payu'>, price_model=<PriceModel.LINEAR: 'linear'>, fixed_price=0.004, price_for={<Counter.TIME: 'golem.usage.duration_sec'>: 0.0008333333333333334, <Counter.CPU: 'golem.usage.cpu_sec'>: 0.0008333333333333334})
[2021-10-29T19:42:17.020-0700 DEBUG yapapi.executor] Scored offer R-969788ffd4ee4e533ce1c774aa9a0cbb37e01a1e9e5f398a25a95ff37dac8cb9, provider: cooing-lift, strategy: DecreaseScoreForUnconfirmedAgreement, score: 89.766607
[2021-10-29T19:42:17.020-0700 DEBUG yapapi.events] ProposalConfirmed(prop_id='R-969788ffd4ee4e533ce1c774aa9a0cbb37e01a1e9e5f398a25a95ff37dac8cb9')
[2021-10-29T19:42:17.028-0700 DEBUG yapapi.events] ProposalReceived(prop_id='R-7ab1c15461e4647c1dc125b5a36b8daa722bffee96c0104cc81b87cec20ffdf8', provider_id='0x35f14eb8d8e4b0685199115c563280916cc90ce7')
[2021-10-29T19:42:17.029-0700 DEBUG yapapi.strategy.LeastExpensiveLinearPayuMS] Scoring offer R-7ab1c15461e4647c1dc125b5a36b8daa722bffee96c0104cc81b87cec20ffdf8, parameters: ComLinear(scheme=<BillingScheme.PAYU: 'payu'>, price_model=<PriceModel.LINEAR: 'linear'>, fixed_price=0.0, price_for={<Counter.TIME: 'golem.usage.duration_sec'>: 5.555555555555556e-06, <Counter.CPU: 'golem.usage.cpu_sec'>: 2.777777777777778e-05})
[2021-10-29T19:42:17.029-0700 DEBUG yapapi.executor] Scored offer R-7ab1c15461e4647c1dc125b5a36b8daa722bffee96c0104cc81b87cec20ffdf8, provider: erar02, strategy: DecreaseScoreForUnconfirmedAgreement, score: 98.814229
[2021-10-29T19:42:17.029-0700 DEBUG yapapi.events] ProposalConfirmed(prop_id='R-7ab1c15461e4647c1dc125b5a36b8daa722bffee96c0104cc81b87cec20ffdf8')
[2021-10-29T19:42:17.124-0700 DEBUG yapapi.agreements_pool] New agreement. id: c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c, provider: NodeInfo(name='erar02', subnet_tag='devnet-beta.2')
[2021-10-29T19:42:17.124-0700 DEBUG yapapi.events] AgreementCreated(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c', provider_id='0x35f14eb8d8e4b0685199115c563280916cc90ce7', provider_info=NodeInfo(name='erar02', subnet_tag='devnet-beta.2'))
[2021-10-29T19:42:17.125-0700 INFO yapapi.summary] Agreement proposed to provider 'erar02'
[2021-10-29T19:42:17.848-0700 INFO yapapi.summary] Received proposals from 2 providers so far
[2021-10-29T19:42:18.721-0700 DEBUG yapapi.events] AgreementConfirmed(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c')
[2021-10-29T19:42:18.722-0700 INFO yapapi.summary] Agreement confirmed by provider 'erar02'
[2021-10-29T19:42:18.722-0700 DEBUG yapapi.events] WorkerStarted(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c')
[2021-10-29T19:42:20.624-0700 INFO yapapi.services] <ShardService: 7b65201f310442e88bd02a65c1503bd5> commissioned
[2021-10-29T19:42:20.624-0700 DEBUG yapapi.events] ActivityCreated(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c', act_id='7b65201f310442e88bd02a65c1503bd5')
[2021-10-29T19:42:20.625-0700 DEBUG yapapi.events] TaskStarted(task_id='1:1', agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c', task_data='Service: ShardService')
[2021-10-29T19:42:20.640-0700 INFO yapapi.summary] Task started on provider 'erar02', task data: Service: ShardService
[2021-10-29T19:42:21.222-0700 DEBUG yapapi.events] ScriptSent(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c', script_id='1', cmds=[{'deploy': {}}, {'start': {'args': ()}}, {'run': {'entry_point': '/bin/mongod', 'args': ('--dbpath', '/shard/db', '--logpath', '/var/log/mongodb/mongod.log', '--fork'), 'capture': {'stdout': {'stream': {}}, 'stderr': {'stream': {}}}}}])
[2021-10-29T19:42:21.222-0700 DEBUG yapapi.summary] Script '1' sent to provider 'erar02', cmds: deploy, start, run
[2021-10-29T19:42:46.966-0700 DEBUG yapapi.rest.payment] Received invoice event: {'event_date': datetime.datetime(2021, 10, 30, 2, 42, 46, 403000, tzinfo=tzutc()),
 'invoice_id': '7e663cfa-0d1b-47e3-b987-62eda783a11b'}, type: <class 'yapapi.rest.configuration._InvoiceReceivedEventWithDate'>
[2021-10-29T19:42:47.240-0700 DEBUG yapapi.events] ProposalReceived(prop_id='R-0aacc7e914da2209138db6fb1029c5f15d5c6fc923d84f75ef01fa4dccc24766', provider_id='0x046fe196e8eb4900d2c1aba91a01d4523ad9fbe5')
[2021-10-29T19:42:47.240-0700 DEBUG yapapi.strategy.LeastExpensiveLinearPayuMS] Scoring offer R-0aacc7e914da2209138db6fb1029c5f15d5c6fc923d84f75ef01fa4dccc24766, parameters: ComLinear(scheme=<BillingScheme.PAYU: 'payu'>, price_model=<PriceModel.LINEAR: 'linear'>, fixed_price=0.0, price_for={<Counter.TIME: 'golem.usage.duration_sec'>: 0.0, <Counter.CPU: 'golem.usage.cpu_sec'>: 0.0})
[2021-10-29T19:42:47.240-0700 DEBUG yapapi.executor] Scored offer R-0aacc7e914da2209138db6fb1029c5f15d5c6fc923d84f75ef01fa4dccc24766, provider: TroggoMan_1, strategy: DecreaseScoreForUnconfirmedAgreement, score: 99.009901
[2021-10-29T19:42:47.240-0700 DEBUG yapapi.events] ProposalConfirmed(prop_id='R-0aacc7e914da2209138db6fb1029c5f15d5c6fc923d84f75ef01fa4dccc24766')
[2021-10-29T19:42:47.869-0700 INFO yapapi.summary] Received proposals from 3 providers so far
[2021-10-29T19:43:16.127-0700 DEBUG yapapi.services] Cluster 1: 1x[Service: ShardService, Payload: _VmPackage(repo_url='http://girepo.dev.golem.network:8000', image_hash='0a4c65ecfd19a1f45e1f9cf77a2da633fcb22f1dea786c261d26af46', constraints=_VmConstraints(min_mem_gib=4, min_storage_gib=16.0, min_cpu_threads=1, runtime='vm'))] is shutting down...
[2021-10-29T19:43:16.127-0700 DEBUG yapapi.services] Waiting for service instances to terminate...
[2021-10-29T19:43:26.129-0700 DEBUG yapapi.services] Cancelling task: <Task pending name='Task-15' coro=<Cluster.spawn_instance() running at /home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py:594> wait_for=<Task pending name='Task-40' coro=<Cluster.spawn_instance.<locals>.start_worker() running at /home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py:566> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb5d2a10910>()]> cb=[<TaskWakeupMethWrapper object at 0x7fb5d133dbe0>()]>>
[2021-10-29T19:43:26.130-0700 DEBUG yapapi.events] PaymentPrepared(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c')
[2021-10-29T19:43:26.130-0700 DEBUG yapapi.events] PaymentQueued(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c')
[2021-10-29T19:43:26.133-0700 DEBUG yapapi.agreements_pool] Terminating agreement. id: c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c, reason: {'message': 'Work cancelled', 'golem.requestor.code': 'Cancelled'}, provider: erar02
[2021-10-29T19:43:26.607-0700 DEBUG yapapi.rest.market] terminateAgreement(c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c) returned successfully
[2021-10-29T19:43:26.608-0700 DEBUG yapapi.rest] Destroying activity 7b65201f310442e88bd02a65c1503bd5 on error:
Traceback (most recent call last):
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py", line 566, in start_worker
    await self._engine.process_batches(agreement.id, act, instance_batches)
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 556, in process_batches
    results = await get_batch_results()
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py", line 537, in get_batch_results
    async for evt_ctx in remote:
  File "/home/controlc/.local/lib/python3.9/site-packages/yapapi/rest/activity.py", line 221, in __aiter__
    await asyncio.sleep(delay)
  File "/usr/lib/python3.9/asyncio/tasks.py", line 654, in sleep
    return await future
asyncio.exceptions.CancelledError
[2021-10-29T19:43:26.609-0700 DEBUG yapapi.events] AgreementTerminated(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c', reason={'message': 'Work cancelled', 'golem.requestor.code': 'Cancelled'})
[2021-10-29T19:43:26.609-0700 INFO yapapi.summary] Terminated agreement with erar02
[2021-10-29T19:43:26.610-0700 DEBUG yapapi.events] ProposalReceived(prop_id='R-26df3656b893311b198a148cc9dc4689cded8fd54f50fb0c7ef1da0a662ca522', provider_id='0x35f14eb8d8e4b0685199115c563280916cc90ce7')
[2021-10-29T19:43:26.611-0700 DEBUG yapapi.strategy.LeastExpensiveLinearPayuMS] Scoring offer R-26df3656b893311b198a148cc9dc4689cded8fd54f50fb0c7ef1da0a662ca522, parameters: ComLinear(scheme=<BillingScheme.PAYU: 'payu'>, price_model=<PriceModel.LINEAR: 'linear'>, fixed_price=0.0, price_for={<Counter.TIME: 'golem.usage.duration_sec'>: 5.555555555555556e-06, <Counter.CPU: 'golem.usage.cpu_sec'>: 2.777777777777778e-05})
[2021-10-29T19:43:26.611-0700 DEBUG yapapi.executor] Scored offer R-26df3656b893311b198a148cc9dc4689cded8fd54f50fb0c7ef1da0a662ca522, provider: erar02, strategy: DecreaseScoreForUnconfirmedAgreement, score: 98.814229
[2021-10-29T19:43:27.056-0700 DEBUG yapapi.rest] Activity 7b65201f310442e88bd02a65c1503bd5 destroyed successfully
[2021-10-29T19:43:27.056-0700 DEBUG yapapi.services] Terminating agreements...
[2021-10-29T19:43:27.057-0700 DEBUG yapapi.services] Cancelling task: <Task pending name='Task-13' coro=<Job.find_offers() running at /home/controlc/.local/lib/python3.9/site-packages/yapapi/engine.py:731> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb5d136eca0>()]>>
[2021-10-29T19:43:27.057-0700 DEBUG yapapi.services] Cancelling task: <Task pending name='Task-14' coro=<Cluster.__aenter__.<locals>.agreements_pool_cycler() running at /home/controlc/.local/lib/python3.9/site-packages/yapapi/services.py:318> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fb5d136e340>()]>>
[2021-10-29T19:43:27.061-0700 INFO yapapi.executor] Golem is shutting down...
[2021-10-29T19:43:27.061-0700 DEBUG yapapi.executor] Waiting for the jobs to finish...
[2021-10-29T19:43:27.062-0700 INFO yapapi.executor] All jobs have finished
[2021-10-29T19:43:27.062-0700 INFO yapapi.executor] 1 agreement still unpaid, waiting for invoices...
[2021-10-29T19:43:27.231-0700 DEBUG yapapi.events] ProposalResponded(prop_id='R-26df3656b893311b198a148cc9dc4689cded8fd54f50fb0c7ef1da0a662ca522')
[2021-10-29T19:43:29.007-0700 DEBUG yapapi.rest.payment] Received invoice event: {'event_date': datetime.datetime(2021, 10, 30, 2, 43, 27, 296000, tzinfo=tzutc()),
 'invoice_id': 'e001876a-fa5d-416a-bd81-cc17f6fa5a70'}, type: <class 'yapapi.rest.configuration._InvoiceReceivedEventWithDate'>
[2021-10-29T19:43:29.009-0700 DEBUG yapapi.events] InvoiceReceived(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c', inv_id='e001876a-fa5d-416a-bd81-cc17f6fa5a70', amount='0.000421861152466667')
[2021-10-29T19:43:29.406-0700 DEBUG yapapi.events] PaymentAccepted(agr_id='c9f30c36327c62147dfa4d3291eedc71f533871163a9a6c9efa9e8c442b3488c', inv_id='e001876a-fa5d-416a-bd81-cc17f6fa5a70', amount='0.000421861152466667')
[2021-10-29T19:43:29.406-0700 INFO yapapi.summary] Accepted invoice from 'erar02', amount: 0.000421861152466667
[2021-10-29T19:43:29.406-0700 INFO yapapi.executor] Waiting for Golem services to finish...
[2021-10-29T19:43:29.411-0700 DEBUG yapapi.events] ShutdownFinished(exc_info=None)
[2021-10-29T19:43:29.412-0700 INFO yapapi.summary] Total cost: 0.000421861152466667
[2021-10-29T19:43:29.412-0700 INFO yapapi.summary] Executor has shut down
[2021-10-29T19:43:29.412-0700 DEBUG yapapi.utils] AsyncWrapper's worker task cancelled```

**Comment by ControlCplusControlV** [comment]
Log file above, using requestor script, unsure what the cause is

**Comment by krunch3r76** [comment]
```py
import asyncio
from datetime import datetime, timedelta

from yapapi import Golem
from yapapi.services import Service, ServiceState
from yapapi.log import enable_default_logger, pluralize
from yapapi.payload import vm


class ShardService(Service):


    @staticmethod
    async def get_payload():
        return await vm.repo(
            image_hash="0a4c65ecfd19a1f45e1f9cf77a2da633fcb22f1dea786c261d26af46",
            min_mem_gib=4,
            min_storage_gib=16.0,
        )


    async def start(self):
        async for script in super().start():
            yield script

        script = self._ctx.new_script()
        script.run("/bin/mongod", "--dbpath", "/shard/db", "--logpath", "/var/log/mongodb/mongod.log", "-f", "/etc/mongod.conf.orig","--fork")
        print("MongoDB engine started")
        yield script



    async def run(self):
        while True:
            script = self._ctx.new_script()
            script.run("/bin/python3","PyDriver.py", "--create" , str('{"Hello":"world"}'))

            yield script


async def main():
    REFRESH_INTERVAL_SEC=5
    async with Golem(budget=1.0, subnet_tag="devnet-beta.2") as golem:
        cluster = await golem.run_service(ShardService, num_instances=1)
        start_time = datetime.now()

       # added
        def still_running():
            return any([s for s in cluster.instances if s.is_available])
        # /added

        while datetime.now() < start_time + timedelta(minutes=1):
            for num, instance in enumerate(cluster.instances):
                print(f"Instance {num} is {instance.state.value} on {instance.provider_name}")
            await asyncio.sleep(REFRESH_INTERVAL_SEC)
            
        cluster.stop()
        while(still_running()):
            await asyncio.sleep(2)

if __name__ == "__main__":
    enable_default_logger(log_file="hello.log")

    loop = asyncio.get_event_loop()
    task = loop.create_task(main())
    loop.run_until_complete(task)
```
